services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: error-free-text-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d error-free-text-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  error-free-text-app:
    container_name: error-free-text-container
    image: error-free-text-app:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy